sonar.projectKey=goncahri_Catalogo_Livros_PI_Frontend
sonar.organization=goncahri

sonar.projectName=Catalogo_Livros_PI_Frontend
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=node_modules/**,coverage/**,.github/**,docs/**

sonar.sourceEncoding=UTF-8